// Types for slide scripts, slides/<id>.ts. Generated by dek; `dek sync` rewrites it.
//
//   export default { motion: { growth: 900 }, draw(slide, { t }) {} } satisfies DekSlide;

export {};

declare global {
  /** What `draw` receives for one frame of a beat. */
  interface DekMotionFrame {
    /** 0-based beat index within the slide. */
    index: number;
    /** The beat id, or its 1-based position: the values `data-step` takes. */
    step: string;
    /** Milliseconds since the beat began, from 0 up to the beat's `motion`. */
    t: number;
  }

  /** The default export of a slide script. */
  interface DekSlide {
    /** Milliseconds of motion per beat, keyed like `data-step`. A beat without an entry is drawn once, at t = 0. */
    motion?: Record<string, number>;
    /**
     * Draws the slide at `t`. The runtime owns the clock: video and screenshots seek it,
     * so draw from `t` alone and set everything you touch on every call.
     */
    draw?(slide: HTMLElement, frame: DekMotionFrame): void;
  }
}
