// Types for slide scripts, slides/<id>.ts. Generated by dekc; `dekc sync` rewrites it.
//
//   export default { motion: { growth: 900 }, draw(slide, { t }) {} } satisfies DekcSlide;

export {};

declare global {
  /** What `draw` receives for one frame of a beat. */
  interface DekcMotionFrame {
    /** Beats reached on the slide: 0 as it arrives, k at its k-th beat. */
    index: number;
    /** "0" as the slide arrives; at a beat, its id or 1-based position, the values `data-step` takes. */
    step: string;
    /** Milliseconds since the beat began, from 0 up to the beat's `motion`. */
    t: number;
  }

  /** The default export of a slide script. */
  interface DekcSlide {
    /** Milliseconds of motion per beat, keyed like `step`. A beat without an entry is drawn once, at t = 0. */
    motion?: Record<string, number>;
    /**
     * Draws the slide at `t`. The runtime owns the clock: video and screenshots seek it,
     * so draw from `t` alone and set everything you touch on every call.
     */
    draw?(slide: HTMLElement, frame: DekcMotionFrame): void;
  }
}
