# voice dictionary
[AI]
kana = "エーアイ"

[Bun]
kana = "バン"

[CSS]
kana = "シーエスエス"

[HTML]
kana = "エイチティーエムエル"

[LAN]
kana = "ラン"

[Markdown]
kana = "マークダウン"

[PDF]
kana = "ピーディーエフ"

[TypeScript]
kana = "タイプスクリプト"

[USB]
kana = "ユーエスビー"

[build]
kana = "ビルド"

[data-step]
kana = "データステップ"

[dek]
kana = "デック"

[duration]
kana = "デュレーション"

[id]
kana = "アイディー"

[lint]
kana = "リント"

[ls]
kana = "エルエス"

["script.md"]
kana = "スクリプトエムディー"
